version: "3.9"

services:
  trafficlight:
    build: .
    image: trafficlight_local:latest
    container_name: trafficlight_local
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development



